config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  resources :videos do
    member do
      put "like", to: "videos#upvote"
    end
  end

  devise_for :users
  resources :users, only: :show 
  get '/users', to: 'users#index'

  resources :cities, only: :show 
  get '/cities', to: 'cities#index'

  resources :countries, only: :show 
  get '/countries', to: 'countries#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :videos
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
end

app/models/trick.rb
class Trick < ActiveRecord::Base
  belongs_to :video
  has_and_belongs_to_many :types
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_and_belongs_to_many :tricks

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :graffiti_image, GraffitiImageUploader

  has_many :videos

  def fame
    videos.reduce(0) { |sum, video| sum + video.get_likes.size }
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :videos
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  belongs_to :vehicle
  belongs_to :city
  has_many   :tricks

  acts_as_votable
  accepts_nested_attributes_for :tricks, allow_destroy: true 

  default_scope { order('created_at DESC') }
  scope :posted_by, -> (n) { where(user: n) }

  # def self.posted_by(person)
  #   where(user: person)
  # end

  def total_likes
    get_likes.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
    # my custom fields are :username, :image
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:username, :image, :email, :password, :password_confirmation, :graffiti_image)
      end

      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:username, :image, :email, :password, :password_confirmation, :current_password, :graffiti_image)
      end
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @videos = Video.where(city_id: @city.id)
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
  end

  def show
    @country = Country.find(params[:id])
    @cities = City.all
  end
end

app/controllers/javascripts_controller.rb
class JavascriptsController < ApplicationController

  def dynamic_cities
    @cities = City.all
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    # @videos = Video.where(user_id: current_user.id)
    @videos = Video.posted_by(current_user)
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :graffiti_image)
    end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  def index
    @videos = Video.all
  end

  def show
    @tricks = Trick.all
  end

  def new
    @cities = City.all
    @video = current_user.videos.new
  end

  def edit
  end

  def create
    @video = current_user.videos.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_user.videos.find(params[:id]).destroy!
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @video = Video.find(params[:id])
    @video.liked_by current_user
    redirect_to @video
  end

  private
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:user_id, :vehicle_id, :city_id, :title, :description, :url, tricks_attributes: [:id, :comment, :timestamp, :type_ids, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/javascripts_helper.rb
module JavascriptsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/application/_navigation.html.erb
<div class="navigation">
  <div class="icon-bar five-up">
    <a class="item" href="/">
    <%= image_tag 'home-icon.png' %>
    </a>
    <a class="item" href="/videos">
      <label>FEED</label>
    </a>
    <a class="item" href="/users">
      <label>MATES</label>
    </a>
    <a class="item" href="/countries">
      <label>GLOBAL</label>
    </a>
    <a class="item" data-method="delete" href="/users/sign_out">
      <label>LEAVE</label>
    </a>
  </div>
</div>

app/views/cities/index.html.erb
<h1>CITIES.</h1>

<ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
  <% @cities.each do |city| %>
    <li class="slide">
      <div class="display_tile">
        <%= link_to image_tag(city.image), city_path(city.id) %>
        <h2><%= city.name %></h2>
      </div>
    </li>
 <% end %>
</ul>

app/views/cities/show.html.erb
<h1><%= @city.name.capitalize %></h1>
<%= render @videos %>

app/views/countries/index.html.erb
<h1>GLOBAL.</h1>

<ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
  <% @countries.each do |country| %>
    <li class="slide">
      <div class="display_tile">
        <%= link_to image_tag(country.image), country_path(country.id) %>
        <h2><%= country.name + '.' %></h2>
      </div>
    </li>
 <% end %>
</ul>

app/views/countries/show.html.erb
<h1>CITIES.</h1>

<ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
  <% @cities.each do |city| %>
    <% if city.country_id == @country.id %>
    <li class="slide">
      <div class="display_tile">
        <%= link_to image_tag(city.image), city_path(city.id) %>
        <h2><%= city.name %></h2>
      </div>
    </li>
    <% else %>
    <% end %>
  <% end %>
</ul>

app/views/users/_user.html.erb
<div class="userinfo small-12 large-6 columns">
  <% if user.graffiti_image.present? %>
    <%= link_to image_tag(user.graffiti_image.url), user_path(user.id) %>
  <% else %>
    <%= link_to image_tag(user.image), user_path(user.id) %>
  <% end %>    
  <div class="usernamefame">
    <h2><%= user.username + '.'%></h2>
    <p>fame <%= user.fame %></p>
  </div>
</div>

app/views/users/index.html.erb
<h1>MATES.</h1>
<div class="useronly userblock">
  <%= render @users %>
</div>

app/views/users/show.html.erb
<div class="userinfo">
<% if @user.graffiti_image.present? %>
  <%= image_tag @user.graffiti_image.url %>
<% else %>
  <%= image_tag @user.image %>
<% end %>
  <div class="usernamefame">
    <h2><%= @user.username + '.' %></h2>
    <p>fame <%= @user.fame %></p>
  </div>
</div>

<%= render @user.videos %>

app/views/videos/_form.html.erb
<div class="formblock">
  <%= nested_form_for @video do |f| %>
  <% if @video.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

    <ul>
      <% @video.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="videoform">

    <h2>video info.</h2>
    <div class="field">
      <%= f.label :vehicle_id %>
      <%= f.collection_select(:vehicle_id, Vehicle.all, :id, :name) %>
    </div>
    <div class="field" id="city_field">
      <label for="video_state_id">City</label>
      <%= f.collection_select(:city_id, City.all, :id, :name) %>
    </div>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :add_code_from_youtube_url %>
      <%= f.text_field :url %>
    </div>

  </div>


  <h2>tricks.</h2>

  <%= f.fields_for :tricks do |t| %>
  <div class="videoform">

    <div class="field">
      <div class="timestamp">
        <%= t.label :timestamp %>
        <span class="datetime">
          <%= t.time_select :timestamp, include_seconds: true, prompt: {hour: 'hours', minute: 'minutes', second: 'seconds'} %>
        </span>
      </div>
    </div>

    <div class="field">
      <%= t.label :comment %>
      <%= t.text_field :comment %>
    </div>

    <div class="field">
      <%= t.label :trick_type %>
      <%= t.collection_select :type_ids, Type.all, :id, :name  %>
    </div>

    <div class="btn"><%= t.link_to_remove "REMOVE TRICK." %></div>
  </div>

  <% end %>

  <div class="btn"><div class="space"></div><%= f.link_to_add "ADD TRICK.", :tricks %></div>

  <div class="actions">
    <%= f.submit "CREATE VIDEO" %>
  </div>
  <% end %>
</div>

app/views/videos/_video.html.erb
<div class="videorow slide">  
  <ul class="small-block-grid-2 medium-block-grid-2 large-block-grid-2 videobox">
    <li class="left">
      <a href="/videos/<%= video.id %>">
        <img src="https://img.youtube.com/vi/<%= video.url %>/hqdefault.jpg">
      </a>
    </li>
    <li class="right">
      <h2><%= video.title + '.'%></h2>
      <h3><%= video.description %></h3> 
      <p><%= video.total_likes %> fame </p>
      <% if current_page? root_path %>
        <%= button_to "EDIT.", edit_video_path(video.id), :method => "get" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/videos/edit.html.erb
<h1>EDIT.</h1>

<div class="newvideo">
  <%= render 'form' %>
</div>

app/views/videos/index.html.erb
<h1>FEED.</h1>

<%= render @videos %>

app/views/videos/new.html.erb
<h1>NEW VID.</h1>

<div class="newvideo">
  <%= render 'form' %>
</div>

app/views/videos/show.html.erb
<div class="videotitle">
  <h1><%= @video.title + '.' %></h1>
</div>

<iframe src="https://www.youtube.com/embed/<%= @video.url %>"></iframe>

<div class="videoshow">
  <%= link_to "UPFAME.", like_video_path(@video), method: :put %>
  <% if @video.user_id == current_user.id %> 
  <%= link_to 'EDIT.', edit_video_path(@video) %>
  <%= link_to 'DELETE.', @video, method: :delete %> 
  <% end %><br>

  <p><%= @video.description %></p>

  <div class="fameshow">
    <h2><%= @video.votes_for.size %> FAME.</h2>
  </div>

  <h2>tricks.</h2>

  <div class="trickshow">
    <% @tricks.each do |trick| %>
    <% if trick.video_id == @video.id %>
    <ul class="small-block-grid-3 trickrow">
      <li><p><%= trick.timestamp.strftime("%M:%S") %></p></li>
      <li>
        <p><% trick.types.each do |type| %>
         <%= type.name + '.' %>
         <% end %>
       </p>
     </li>
     <li><p><%= trick.comment %></p></li>
    </ul>
    <% else %>
    <% end %>
    <% end %>
 </div>

</div>